### ISSUE TITLE
Caching(?) causes the html field to not be returned from an API request

### ISSUE THREAD

**Issue by essential-randomness** [itteco/iframely#281] opened 2020-08-30 22:57 UTC
Hello,
I've been using iframely hosted on GAE to serve embeds for my website, using the present released version (on master). [This is an example of an API request to my endpoint](https://embeds-dot-bobaboard.uc.r.appspot.com/iframely?url=https://www.reddit.com/r/gifs/comments/iaxkas/disintegrate_your_haters/&iframe=0)

For some reason, the "html" field in the response appears and disappears intermittently. This seems related to caching, as switching endpoint or api parameters makes the field reappear. When the html field disappears, subsequent requests with different parameters still log "using cached response for reddit", but return once again all the fields.

My best guess is that the server caches both its own responses and the responses it gets from reddit. So when making a request of the same content but with different parameters, it correctly reuses the data it cached from reddit, but with the same parameters it sometimes reuses a response that has been cached incorrectly.

If this is the expected behavior, I couldn't find any mention of it in the documents or anywhere else. Any idea what might be going on?

Thank you.

**Comment by essential-randomness** [comment] 2020-09-11 00:02
Hi. Wanted to bump this. It's still happening and I'm not closer to finding a solution.

**Comment by iparamonau** [comment] 2020-09-11 01:16
Hey, sorry about neglecting this. Is it just for Reddit that you see this happening, or it happens with all providers across the board?

**Comment by essential-randomness** [comment] 2020-09-11 03:13
All providers (or, at least, I've seen the same thing for pixiv). I've tried to add a &test=(random number) to the end of the request URL and it makes the html field appear again, though it still won't appear in the original request if reverted. 

I'll try this in production later to confirm that that itself is enough to solve the issue in all cases. Of course, would love to rootcause.

**Comment by iparamonau** [comment] 2020-09-16 13:55
The config option that is responsible for cache is `CACHE_TTL: 0`. If you set it, it will be responsible for both Reddit oEmbed cache and the cache of the Iframely response.

Your issue looks like is caused by some Reddit exception. If they return an error, Iframely will cache their oEmbed response for that URL (and so - no HTML). 

When you change the URL itself by appending querystring, the oEmbed endpoint address also changes (as it adds `&url=...` there). And so you end up busting oEmbed cache as well. 

So the caching issue works as expected here. I'll close the issue for now. Please do open a separate issue for root cause if you find our what the error response is that you get from Reddit.

**Closed by iparamonau** 2020-09-16 13:55 UTC

**Comment by iparamonau** [comment] 2020-09-16 14:13
Just to be 100% accurate. 

Your `to add a &test=(random number) to the end of the request URL` - can mean two things. 1) You add the param to the URL itself, and 2) you add it at the end of the API call. 

Both ways will bust Iframely response cache - true. If you change the URL itself, you will also bust the oEmbed cache for Reddit (as full URL is in the cache key).  However, if you only change query string for the API call and leave `&url=...` as it was, this won't bust oEmbed cache - it will persist for your `CACHE_TTL` setting. 

So if 2) is your fix, then it means that there was no OK oEmbed response from Reddit initially and so there was no cache. Errors are not cached. When you change the API call query-string, it bypasses the cache of Iframely API response, and fetches oEmbed a new on the cache-miss.

**Comment by featherbutt** [comment] 2020-09-28 03:40
The initial result from reddit was cached. From the original issue description: "When the html field disappears, subsequent requests with different parameters still log "using cached response for reddit", but return once again all the fields."

I also confirmed with @essential-randomness that it wasn't just requests to reddit that were having this issue, but Pixiv too.
