### ISSUE TITLE
Youtube embeds show device support warning

### ISSUE THREAD

**Issue by OKNoah** [itteco/iframely#66] opened 2015-05-12 21:30 UTC
All my embeds are showing this video:

https://www.youtube.com/watch?v=UKY3scPIMd8

Is this related to iFramely?

**Comment by iparamonau** [comment] 2015-05-13 00:58
It is, yes. This error is definitely caused by Iframely. 

It should be fixed though. Let's see why you still see the error.

1) New YouTube plugin requires API key for YouTube API v3. See sample config
2) Even with no API key, Iframely should be falling back to plain oEmbed. Somewhat limited, but you shouldn't see this error. 
3) Which makes me think the problem is in the cache. Indeed, if you don't have YouTube API key configured, domain plugin is ignored and Iframely won't be able to tell that old plugin changed and so to request URLs to re-cache. 

This said:
- Can you confirm please that it works for you on new URLs (before entering the key)
- After you entered the key - let us know if the cache didn't re-invalidate itself.

**Comment by manikmi** [comment] 2015-05-13 01:19
Hi All,

For me it worked without key, but if I enter the key it returned error on
console as "Youtube returned with Page not found 404".

Regards,
Manik Mittal

On Wed, May 13, 2015 at 6:28 AM, Ivan Paramonau <notifications@github.com>
wrote:

> It is, yes. This error is definitely caused by Iframely.
>
> It should be fixed though. Let's see why you still see the error.
>
> 1) New YouTube plugin requires API key for YouTube API v3. See sample
> config
> 2) Even with no API key, Iframely should be falling back to plain oEmbed.
> Somewhat limited, but you shouldn't see this error.
> 3) Which makes me think the problem is in the cache. Indeed, if you don't
> have YouTube API key configured, domain plugin is ignored and Iframely
> won't be able to tell that old plugin changed and so to request URLs to
> re-cache.
>
> This said:
>
>    - Can you confirm please that it works for you on new URLs (before
>    entering the key)
>    - After you entered the key - let us know if the cache didn't
>    re-invalidate itself.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/itteco/iframely/issues/66#issuecomment-101472794>.
>



-- 
Regards,
Manik Mittal

**Comment by iparamonau** [comment] 2015-05-13 01:47
@manikmi you probably have not enabled YouTube in your Google developer access. You need to do it of Maps and YouTube separately.

**Comment by OKNoah** [comment] 2015-05-13 20:48
After adding the API key, it works. Sorry, I'm not sure about old or new videos in the cache. Also, there was a bit of a problem with my Angular directive.

**Comment by iparamonau** [comment] 2015-05-13 21:07
Ok I'll close it for now then. Your cache should be all right too.

**Closed by iparamonau** 2015-05-13 21:07 UTC
